[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --port=/dev/cu.usbmodem1101 --chip esp32s3"
rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
CARGO_FEATURE_ESP_IDF = "1" 
WAMR_BUILD_TARGET = "XTENSA"
